name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: su ./configure
    - name: make
      run: su make
    - name: make check
      run: su make check
    - name: make distcheck
      run: su make distcheck
       
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: artifact
        path: ./

